version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node_with_nginx_network

  node:
    build: 
      context: ./node
    container_name: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node app.js
    tty: true
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - node_with_nginx_network

  nginx:
    build: 
      context: ./nginx
    container_name: nginx
    tty: true
    ports:
      - '8080:80'
    networks:
      - node_with_nginx_network

networks:
  node_with_nginx_network:
    driver: bridge